version: '3.7'

services:
    app:
        image: docker.local/jenkins-test/jenkins-test-deploy
        build:
            context: .
        
        ports: 
            - '8000:8000'
        
        volumes:
            - ./app:/app
        
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
