version: '3.7'

services:
    app:
        build:
            context: .
        
        image: jenkins-test
        
        ports: 
            - '8000:8000'
        
        volumes:
            - ./app:/app
        
        command: bash -c "python manage.py migrate && python manage.py test"
